/*

 COIN.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char coin_sprite[] =
{
  0x3C,0x3C,0x4E,0x42,0x87,0x99,0x93,0xA5,
  0xD3,0xA5,0xE7,0x99,0x7E,0x42,0x3C,0x3C
};

/* End of COIN.C */
