/*

 EXPORT.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char snake_sprite[] =
{
  0xFF,0x00,0x99,0x66,0xBD,0x66,0xE7,0x18,
  0xDB,0x3C,0xFF,0x3C,0xDB,0x24,0xFF,0x00
};

/* End of EXPORT.C */
