/*

 SNAKE_GAME_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\barba\Desktop\gbtdbackground\materials\complete_walls.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define snake_game_mapWidth 20
#define snake_game_mapHeight 18
#define snake_game_mapBank 0

extern unsigned char snake_game_map[];

/* End of SNAKE_GAME_MAP.H */
